--- #YAML:1.0
name:               Csistck
version:            0.06
abstract:           Perl system consistency check framework
author:
    - Anthony Johnson <aj@ohess.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:          0
    File::Basename:       0
    File::Copy:           0
    File::stat:           0
    Getopt::Long:         0
    Sys::Hostname::Long:  0
    Template:             0
    Term::ReadKey:        0
    Test::Exception:      0
    Text::Diff:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
